name: modular_api_sqlserver
description: Official MACSS SQL Server integration package for Dart.
version: 0.5.0

repository: https://github.com/macss-dev/modular_api/tree/main/code/dart/modular_api_sqlserver
homepage: https://github.com/macss-dev/modular_api
issue_tracker: https://github.com/macss-dev/modular_api/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dart_odbc: ^6.2.0
  modular_api: ^0.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.28.0