"""OpenAPI 3.0 spec generation from api_registry.

Iterates all ``UseCaseRegistration`` entries and builds a complete
OpenAPI 3.0.0 spec object with paths, components/schemas, and
operation metadata.

Mirror of ``OpenApi.jsonStringFromSchema()`` in Dart and
``buildOpenApiSpec()`` in TypeScript.
"""

from __future__ import annotations

import json
import re
from typing import Any

from starlette.requests import Request
from starlette.responses import Response

from modular_api.core.registry import UseCaseRegistration, api_registry


def build_openapi_spec(
    *,
    title: str,
    port: int,
    version: str = "0.1.0",
    description: str = "Auto-generated by modular_api",
    servers: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Build a complete OpenAPI 3.0.0 specification from registered routes.

    Each ``UseCaseRegistration`` in ``api_registry.routes`` contributes
    a path entry, requestBody or parameters, response schemas, and
    operation metadata (tags, summary, operationId).
    """
    default_servers = [{"url": f"http://localhost:{port}", "description": "Local"}]

    paths: dict[str, dict[str, Any]] = {}
    component_schemas: dict[str, Any] = {}

    for route in api_registry.routes:
        _add_route_to_spec(route, paths, component_schemas)

    return {
        "openapi": "3.0.0",
        "info": {"title": title, "version": version, "description": description},
        "servers": servers or default_servers,
        "paths": paths,
        "components": {"schemas": component_schemas},
    }


# ── Endpoint factories ────────────────────────────────────────


def openapi_json_handler(*, title: str, port: int, **kwargs: Any) -> Any:
    """Return a Starlette endpoint that serves the OpenAPI spec as JSON."""

    async def endpoint(request: Request) -> Response:
        spec = build_openapi_spec(title=title, port=port, **kwargs)
        return Response(
            content=json.dumps(spec, indent=2),
            media_type="application/json; charset=utf-8",
        )

    return endpoint


def openapi_yaml_handler(*, title: str, port: int, **kwargs: Any) -> Any:
    """Return a Starlette endpoint that serves the OpenAPI spec as YAML."""

    async def endpoint(request: Request) -> Response:
        spec = build_openapi_spec(title=title, port=port, **kwargs)
        return Response(
            content=json_to_yaml(spec),
            media_type="application/x-yaml; charset=utf-8",
        )

    return endpoint


# ── Spec builder internals ────────────────────────────────────


def _add_route_to_spec(
    route: UseCaseRegistration,
    paths: dict[str, dict[str, Any]],
    component_schemas: dict[str, Any],
) -> None:
    """Append a single route's path entry, schemas, and operation to the spec."""
    safe_command = route.command.replace("-", "_")
    input_ref_name = f"{route.module}_{safe_command}_Input"
    output_ref_name = f"{route.module}_{safe_command}_Output"

    # Store schemas in components
    component_schemas[input_ref_name] = route.schemas.get("input", {"type": "object"})
    component_schemas[output_ref_name] = route.schemas.get("output", {"type": "object"})

    method_lower = route.method.lower()
    tags = route.doc.tags if route.doc and route.doc.tags else [route.module]
    summary = route.doc.summary if route.doc else None
    description = route.doc.description if route.doc else None

    operation: dict[str, Any] = {
        "operationId": f"{route.module}_{safe_command}_{method_lower}",
        "tags": tags,
        "responses": {
            "200": {
                "description": "OK",
                "content": {
                    "application/json": {
                        "schema": {"$ref": f"#/components/schemas/{output_ref_name}"},
                    },
                },
            },
            "400": {"description": "Bad Request"},
            "500": {"description": "Internal Server Error"},
        },
    }

    if summary:
        operation["summary"] = summary
    if description:
        operation["description"] = description

    # GET/DELETE → query parameters; POST/PUT/PATCH → requestBody
    if method_lower in ("get", "delete"):
        operation["parameters"] = _schema_to_query_params(
            route.schemas.get("input", {}),
        )
    else:
        operation["requestBody"] = {
            "required": True,
            "content": {
                "application/json": {
                    "schema": {"$ref": f"#/components/schemas/{input_ref_name}"},
                },
            },
        }

    # Insert into paths (multiple methods on the same path are allowed)
    paths.setdefault(route.path, {})[method_lower] = operation


def _schema_to_query_params(
    schema: dict[str, Any],
) -> list[dict[str, Any]]:
    """Convert a flat JSON Schema (top-level properties) into OpenAPI query parameters."""
    properties = schema.get("properties", {})
    required_set: set[str] = set(schema.get("required", []))

    return [
        {
            "name": prop_name,
            "in": "query",
            "required": prop_name in required_set,
            "schema": {"type": prop_value.get("type", "string")},
        }
        for prop_name, prop_value in properties.items()
    ]


# ── JSON-to-YAML converter (zero dependencies) ───────────────

# YAML reserved words that need quoting when used as values.
_YAML_RESERVED = frozenset(
    {"true", "false", "null", "yes", "no", "on", "off", "y", "n"},
)

# Characters that force quoting in a YAML string.
_YAML_SPECIAL_RE = re.compile(r"[:{}\[\],&*?|>!%#@`\"\\']")


def _needs_quoting(text: str) -> bool:
    """Return True if a string value or key needs single-quoting in YAML."""
    if not text:
        return True
    if text.lower() in _YAML_RESERVED:
        return True
    if _YAML_SPECIAL_RE.search(text):
        return True
    if text[0] in "-? ":
        return True
    # Looks like a number but is semantically a string
    try:
        float(text)
        return True
    except ValueError:
        pass
    if "\n" in text:
        return True
    return False


def _yaml_key(key: str) -> str:
    """Format a YAML key, quoting if necessary."""
    if _needs_quoting(key):
        return f"'{key.replace(chr(39), chr(39)*2)}'"
    return key


def _yaml_scalar(value: object) -> str:
    """Render a YAML scalar (string, number, bool, None)."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if _needs_quoting(text):
        return f"'{text.replace(chr(39), chr(39)*2)}'"
    return text


def json_to_yaml(value: object, *, _indent: int = 0, _is_root: bool = True) -> str:
    """Convert a JSON-decoded Python value to a YAML string.

    Zero dependencies — handles dicts, lists, strings, numbers, bools, and None.
    Mirror of ``OpenApi.jsonToYaml()`` in Dart and ``jsonToYaml()`` in TypeScript.
    """
    pad = "  " * _indent

    if isinstance(value, dict):
        if not value:
            return "{}\n"
        result = "" if _is_root else "\n"
        for k, v in value.items():
            if isinstance(v, (dict, list)):
                result += f"{pad}{_yaml_key(str(k))}:{json_to_yaml(v, _indent=_indent + 1, _is_root=False)}"
            else:
                result += f"{pad}{_yaml_key(str(k))}: {_yaml_scalar(v)}\n"
        return result

    if isinstance(value, list):
        if not value:
            return "[]\n"
        result = "" if _is_root else "\n"
        for item in value:
            if isinstance(item, dict) and item:
                first = True
                for k, v in item.items():
                    prefix = f"{pad}- " if first else f"{pad}  "
                    first = False
                    if isinstance(v, (dict, list)):
                        result += f"{prefix}{_yaml_key(str(k))}:{json_to_yaml(v, _indent=_indent + 2, _is_root=False)}"
                    else:
                        result += f"{prefix}{_yaml_key(str(k))}: {_yaml_scalar(v)}\n"
            elif isinstance(item, (dict, list)):
                result += f"{pad}- {json_to_yaml(item, _indent=_indent + 1, _is_root=False)}"
            else:
                result += f"{pad}- {_yaml_scalar(item)}\n"
        return result

    return f"{_yaml_scalar(value)}\n"
