name: modular_api_rest_client
description: Official MACSS outbound REST client for Dart.
version: 0.6.0

repository: https://github.com/ccisnedev/modular_api/tree/main/code/dart/modular_api_rest_client
homepage: https://github.com/ccisnedev/modular_api
issue_tracker: https://github.com/ccisnedev/modular_api/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ">=1.2.0 <2.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.28.0